# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGohMgZjwOhSUnFVmAjpDcm-GjBeFuPq

# Task 4

imports
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

"""load analysed.csv"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import os

file_path = "/content/drive/MyDrive/data/trends_analysed.csv"

df = pd.read_csv(file_path)

os.makedirs("outputs", exist_ok=True)

print("Loaded data:", df.shape)
print(df.head())

"""Chart 1: top 10 stories by score"""

top_10 = df.nlargest(10, "score").copy()

top_10["short_title"] = top_10["title"].apply(
    lambda x: x[:50] + "..." if len(x) > 50 else x
)

plt.figure(figsize=(12, 6))
plt.barh(top_10["short_title"], top_10["score"], color="skyblue")
plt.xlabel("Score")
plt.ylabel("Title")
plt.title("Top 10 Stories by Score")
plt.gca().invert_yaxis()

plt.tight_layout()
plt.savefig("outputs/chart1_top_stories.png")
plt.show()

"""Chart 2: how many stories came from each category"""

category_counts = df["category"].value_counts()

colors = ["#4c78a8", "#f58518", "#54a24b", "#e45756", "#72b7b2"]

plt.figure(figsize=(8, 5))
plt.bar(category_counts.index, category_counts.values, color=colors[:len(category_counts)])
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")

plt.tight_layout()
plt.savefig("outputs/chart2_categories.png")
plt.show()

"""Chart 3: scatter plot"""

popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

plt.figure(figsize=(8, 6))
plt.scatter(not_popular["score"], not_popular["num_comments"], color="gray", alpha=0.6, label="Not Popular")
plt.scatter(popular["score"], popular["num_comments"], color="red", alpha=0.7, label="Popular")

plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Comments")
plt.legend()

plt.tight_layout()
plt.savefig("outputs/chart3_scatter.png")
plt.show()

"""Dashboard"""

fig, axes = plt.subplots(1, 3, figsize=(20, 6))
fig.suptitle("TrendPulse Dashboard", fontsize=16)

# Chart 1
axes[0].barh(top_10["short_title"], top_10["score"], color="skyblue")
axes[0].set_title("Top 10 Stories by Score")
axes[0].set_xlabel("Score")
axes[0].set_ylabel("Title")
axes[0].invert_yaxis()

# Chart 2
axes[1].bar(category_counts.index, category_counts.values, color=colors[:len(category_counts)])
axes[1].set_title("Stories per Category")
axes[1].set_xlabel("Category")
axes[1].set_ylabel("Count")
axes[1].tick_params(axis="x", rotation=45)

# Chart 3
axes[2].scatter(not_popular["score"], not_popular["num_comments"], color="gray", alpha=0.6, label="Not Popular")
axes[2].scatter(popular["score"], popular["num_comments"], color="red", alpha=0.7, label="Popular")
axes[2].set_title("Score vs Comments")
axes[2].set_xlabel("Score")
axes[2].set_ylabel("Comments")
axes[2].legend()

plt.tight_layout()
plt.savefig("outputs/dashboard.png")
plt.show()

