# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7wtA2hzdy6te52Qys6ulW4bmz_banw0

# Task 2

imports
"""

import pandas as pd

"""load the file"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = "/content/drive/MyDrive/data/trends_20260406.json"   # update filename if needed
df = pd.read_json(file_path)

print("Loaded rows:", len(df))
df.head()

"""Remove duplicates"""

df = df.drop_duplicates(subset="post_id")

print("After removing duplicates:", len(df))

"""Handling Missing Values"""

df = df.dropna(subset=["post_id", "title", "score"])

print("After dropping missing post_id/title/score:", len(df))

"""Fix Datatypes"""

df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].fillna(0).astype(int)

print("Data types fixed:")
print(df[["score", "num_comments"]].dtypes)

"""Remove Low Quality Rows"""

df = df[df["score"] >= 5]

print("After removing low-score stories:", len(df))

"""Strip Extra spaces"""

df["title"] = df["title"].str.strip()

print("Title whitespace cleaned.")

"""save as trends_clean.csv"""

from google.colab import drive
drive.mount('/content/drive')

import os

output_path = "/content/drive/MyDrive/data/trends_clean.csv"
df.to_csv(output_path, index=False)

print(f"Saved {len(df)} rows to {output_path}")
print("\nStories per category:")
print(df["category"].value_counts())

