# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1RAyNEbTNqYGxQ-zXZ2lyLvfO-tm9tX

# Task 3

imports
"""

import pandas as pd
import numpy as np

"""loading trends_clean.csv"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = "/content/drive/MyDrive/data/trends_clean.csv"

df = pd.read_csv(file_path)

print("Loaded data shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())

"""Numpy Analysis"""

scores = df["score"].to_numpy()
comments = df["num_comments"].to_numpy()

mean_score = np.mean(scores)
median_score = np.median(scores)
std_score = np.std(scores)

highest_score = np.max(scores)
lowest_score = np.min(scores)

top_category = df["category"].value_counts().idxmax()

most_comments_index = np.argmax(comments)
most_commented_title = df.iloc[most_comments_index]["title"]
most_commented_count = df.iloc[most_comments_index]["num_comments"]

print("Mean score:", mean_score)
print("Median score:", median_score)
print("Standard deviation of score:", std_score)
print("Highest score:", highest_score)
print("Lowest score:", lowest_score)
print("Category with most stories:", top_category)
print("Story with most comments:", most_commented_title)
print("Comment count:", most_commented_count)

"""Add two columns"""

# 1 — engagement: how much discussion per upvote
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# 2 — is_popular: True if score > average score, else False
average_score = mean_score   # reuse the value you computed
df["is_popular"] = df["score"] > average_score

print(df[["score", "num_comments", "engagement", "is_popular"]].head())

"""save trends_analysed.csv"""

from google.colab import drive
drive.mount('/content/drive')

output_path = "/content/drive/MyDrive/data/trends_analysed.csv"
df.to_csv(output_path, index=False)

print(f"Saved analysed data with {df.shape[0]} rows and {df.shape[1]} columns to {output_path}")