# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrsVepyfozgUHnvzXYdTCtEC2NAFQy62

# Task 1

imports
"""

import requests
import json
import os
import time
from datetime import datetime

"""category keyword mapping"""

category_keywords = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

"""function accept a title as input and return the matching category based on the keyword"""

def title_cate(title):
    if not title:
        return "other"

    title = title.lower()

    for category, keywords in category_keywords.items():
        for keyword in keywords:
            if keyword in title:
                return category

    return "other"

"""request top-story endpoint"""

top_stories_url = "https://hacker-news.firebaseio.com/v0/topstories.json"

response = requests.get(top_stories_url)
response.raise_for_status()

story_ids = response.json()[:500]

print("Total IDs fetched:", len(story_ids))
print("First 10 IDs:", story_ids[:10])

stories = []

for story_id in story_ids:
    try:
        item_url = f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json"
        response = requests.get(item_url)
        response.raise_for_status()

        story = response.json()

        if story is None:
            continue

        title = story.get("title")
        category = title_cate(title)

        if category == "other":
            continue

        story_data = {
            "post_id": story.get("id"),
            "title": title,
            "category": category,
            "score": story.get("score"),
            "num_comments": story.get("descendants", 0),
            "author": story.get("by"),
            "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        stories.append(story_data)

    except Exception as e:
        print(f"Error fetching story {story_id}: {e}")

"""Create a data folder and save the results trends_YYYYMMDD.json"""

os.makedirs("data", exist_ok=True)

today_date = datetime.now().strftime("%Y%m%d")
file_path = f"data/trends_{today_date}.json"

with open(file_path, "w", encoding="utf-8") as f:
    json.dump(stories, f, indent=4, ensure_ascii=False)

print(f"Collected {len(stories)} stories. Saved to {file_path}")

from google.colab import drive
drive.mount('/content/drive')

import os
import json
from datetime import datetime

# Choose a folder inside your Drive
base_dir = "/content/drive/MyDrive/data"

# Create the folder if it doesn't exist
os.makedirs(base_dir, exist_ok=True)

# Build dated filename
today_date = datetime.now().strftime("%Y%m%d")
file_path = f"{base_dir}/trends_{today_date}.json"

# Save JSON
with open(file_path, "w", encoding="utf-8") as f:
    json.dump(stories, f, indent=4, ensure_ascii=False)

print(f"Collected {len(stories)} stories. Saved to {file_path}")

import os

print("data folder exists:", os.path.exists("data"))

if os.path.exists("data"):
    print("Files inside data folder:")
    print(os.listdir("data"))

print("Number of collected stories:", len(stories))
print("Example story:", stories[:1])

print("Number of collected stories:", len(stories))
print(f"Collected {len(stories)} stories. Saved to {file_path}")

import os
print(os.path.exists("data"))
print(os.listdir("data"))

import os
print("data exists:", os.path.exists("data"))
print("files:", os.listdir("data") if os.path.exists("data") else "no data folder")

import os
import pandas as pd

file_path = "data/trends_20260406.json"   # use the exact name you saw

if not os.path.exists(file_path):
    raise FileNotFoundError(f"{file_path} not found. Run Task 1 first in this environment.")

df = pd.read_json(file_path)

print("Loaded rows:", len(df))
print(df.head())

import os
print(os.getcwd())

# task1_fetch.py

import os
import json
from datetime import datetime
import requests

def main():
    # 1. collect stories (you already have this logic)
    stories = []  # <-- your existing collection logic goes here

    # 2. make sure data/ exists
    data_dir = "data"
    os.makedirs(data_dir, exist_ok=True)

    # 3. build filename with date
    today_date = datetime.now().strftime("%Y%m%d")
    file_path = os.path.join(data_dir, f"trends_{today_date}.json")

    # 4. save JSON
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(stories, f, indent=4, ensure_ascii=False)

    print(f"Collected {len(stories)} stories. Saved to {file_path}")

if __name__ == "__main__":
    main()

